[package]
name = "Pixel-Planet-Portal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "3"
tera = "1.5.0"
serde = "1.0" 
